version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build started
      - echo "Hello World Build"
artifacts:
  files:
    - '**/*'
  name: build-artifact